// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub vaults: ::prost::alloc::vec::Vec<Vault>,
    #[prost(message, repeated, tag="2")]
    pub positions: ::prost::alloc::vec::Vec<Position>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vault {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token0: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub token1: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub vault_id: u64,
    #[prost(uint64, tag="5")]
    pub block_number: u64,
    #[prost(string, tag="6")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub factory: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Position {
    #[prost(uint64, tag="1")]
    pub position_id: u64,
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount0: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount1: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub block_number: u64,
    #[prost(string, tag="6")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub vault: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
